### ISSUE TITLE
BBBAdministratorlogin does not work

### ISSUE THREAD

**Issue by virilc** [aws-samples/aws-scalable-big-blue-button-example#113]
**Describe the bug**
Deployed the latest version. Everything else works except for the Administrator login found in Secrets Manager.

**To Reproduce**
1. Go to conference.bbbdomain.xxxx after a successful deployment.
2. Click "Sign in".
3. Go to Secrets Manager to retrieve the username and password from the BBBAdministratorlogin-xxxxx secret.
4. Try to sign in using the retrieved credentials.
5. Cannot login. Error: "The email and password you entered did not match our records. Try again or click Forgot Password to reset your password."

**Expected behavior**
Successful login to the Administrator console.

**Screenshots**
![bbb_admin_login_error](https://user-images.githubusercontent.com/59304816/170489261-e3cf044d-0a60-46e7-bd92-fbc1473031bc.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Firefox
 - Version: Latest

**Smartphone (please complete the following information):**
N/A

**Additional context**
Forgot password, also not working.

**Comment by jonnyfux** [comment]
Did you try restarting the greenlight task? See this thread https://github.com/aws-samples/aws-scalable-big-blue-button-example/issues/99#issuecomment-878825233

**Comment by virilc** [comment]
@jonnyfux Just tried, same issue. By the way, checked logs, saw something about password complexity error. Possibly related but don't know where to look to fix it. I just know how to test and report errors. :D

![BBBAdministratorlogin_logs_error_password_complexity](https://user-images.githubusercontent.com/59304816/170648950-affef4a8-cf3f-46ca-929d-a28135841359.png)

**Comment by couchgott** [comment]
educated guess: 

BBBAdministratorlogin:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: ‘This is the BBB base secret’
      GenerateSecretString:
        SecretStringTemplate: !Sub “{\“username\“:\“${BBBOperatorEMail}\“}”
        GenerateStringKey: ‘password’
        PasswordLength: 16
        ExcludePunctuation: true

line 302-310 at bbb-on-aws-frontendapps.template.yaml

Puncutation needs to be allowed. afaik we disabled due some chars breaking the env for the tasks. need to test that.

**Comment by couchgott** [comment]
this is solved and tested with release 3.0.7 and 4.0.0

**Comment by kurt-plaza** [comment]
Is this error result for Fargate? I update the ECS, I reinstall, but I still don't have access to the platforms with the secret manager keys.
